import OpenIn from "@/components/OpenIn";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>David Hwang</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-customBlack h-screen text-customWhite">
        <div className="flex flex-column flex-wrap h-screen justify-center">
          <div className="flex flex-wrap gap-x-10 max-sm:gap-x-5 justify-center self-end">
            <div className="profile-image-container mb-10 flex justify-end lg:w-5/12 md:w-5/12 sm:w-8/12">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="/profile.png"
                alt="profile image"
                className="object-contain rounded-xl max-sm:rounded-full max-sm:border-4 max-sm:border-customOrange max-sm:p-1"
              />
            </div>
            <div className="grow text-left max-sm:text-center max-sm:px-5 mb-10">
              <p className="w-full text-3xl max-sm:text-xl font-light">
                Hello, world! I&apos;m
              </p>
              <p className="w-full text-5xl max-sm:text-4xl text-customOrange font-bold my-3">
                David Hwang
              </p>
              <p className="w-full text-3xl max-sm:text-xl font-light">
                I&apos;m currently a senior studying
              </p>
              <p className="w-full text-3xl max-sm:text-xl font-bold text-customOrange">
                Electrical &amp; Computer Engineering
              </p>
              <p className="w-full text-3xl max-sm:text-xl font-light">
                at{" "}
                <span className="text-customOrange font-bold">
                  Carnegie Mellon University
                </span>
              </p>
            </div>
            <div className="basis-full h-0" />
            <div className="w-5/12 max-sm:w-4/12 text-right">
              <p>GitHub</p>
              <p>LinkedIn</p>
              <p>Email</p>
            </div>
            <div className="grow">
              <p>
                @hdavidethan{" "}
                <a
                  className="inline-flex align-top text-[1.25rem] cursor-pointer"
                  href="https://github.com/hdavidethan"
                  target="_blank"
                >
                  <OpenIn className="h-[1.25rem]" />
                </a>
              </p>
              <p>
                @h-davidethan{" "}
                <a
                  className="material-symbols-outlined inline-flex align-top text-[1.25rem] cursor-pointer"
                  href="https://linkedin.com/in/h-davidethan"
                  target="_blank"
                >
                  <OpenIn className="h-[1.25rem]" />
                </a>
              </p>
              <p>
                hdavidethan@gmail.com{" "}
                <a
                  className="material-symbols-outlined inline-flex align-top text-[1.25rem] cursor-pointer"
                  href="mailto:hdavidethan@gmail.com"
                  target="_blank"
                >
                  <OpenIn className="h-[1.25rem]" />
                </a>
              </p>
            </div>
          </div>
          <div className="m-10 w-full flex justify-center">
            <a
              className="border-2 border-solid border-customOrange 
            text-customOrange py-2 px-3 rounded-md hover:bg-customOrange
            hover:text-customWhite transition-colors cursor-pointer h-min"
              href="/resume.pdf"
              target="_blank"
            >
              Resume PDF
            </a>
          </div>
        </div>
      </main>
    </>
  );
}
