import OpenIn from "@/components/OpenIn";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>David Hwang</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-customBlack h-screen text-customWhite">
        <div className="flex flex-column flex-wrap h-screen justify-center">
          <div className="flex justify-center items-end flex-row gap-10">
            <div className="flex flex-column flex-wrap text-right w-full gap-1">
              <div className="profile-image-container mb-10 w-full flex justify-end">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src="/profile.png" alt="profile image" />
              </div>
              <p className="w-full">GitHub</p>
              <p className="w-full">LinkedIn</p>
              <p className="w-full">Email</p>
            </div>
            <div className="flex flex-column flex-wrap gap-1">
              <div className="flex flex-column flex-wrap mb-10">
                <p className="w-full text-3xl font-light">
                  Hello, world! I&apos;m
                </p>
                <p className="w-full text-5xl text-customOrange font-bold my-3">
                  David Hwang
                </p>
                <p className="w-full text-3xl font-light">
                  I&apos;m currently a senior studying
                </p>
                <p className="w-full text-3xl font-bold text-customOrange">
                  Electrical &amp; Computer Engineering
                </p>
                <p className="w-full text-3xl font-light">
                  at{" "}
                  <span className="text-customOrange font-bold">
                    Carnegie Mellon Univeristy
                  </span>
                </p>
              </div>
              <p className="w-full">
                @hdavidethan{" "}
                <a
                  className="inline-flex align-top text-[1.25rem] cursor-pointer"
                  href="https://github.com/hdavidethan"
                  target="_blank"
                >
                  <OpenIn className="h-[1.25rem]" />
                </a>
              </p>
              <p className="w-full">
                @h-davidethan{" "}
                <a
                  className="material-symbols-outlined inline-flex align-top text-[1.25rem] cursor-pointer"
                  href="https://linkedin.com/in/h-davidethan"
                  target="_blank"
                >
                  <OpenIn className="h-[1.25rem]" />
                </a>
              </p>
              <p className="w-full">
                hdavidethan@gmail.com{" "}
                <a
                  className="material-symbols-outlined inline-flex align-top text-[1.25rem] cursor-pointer"
                  href="mailto:hdavidethan@gmail.com"
                  target="_blank"
                >
                  <OpenIn className="h-[1.25rem]" />
                </a>
              </p>
            </div>
          </div>
          <div className="m-10">
            <a
              className="border-2 border-solid border-customOrange 
            text-customOrange py-2 px-3 rounded-md hover:bg-customOrange
            hover:text-customWhite transition-colors cursor-pointer"
              href="/resume.pdf"
              target="_blank"
            >
              Resume PDF
            </a>
          </div>
        </div>
      </main>
    </>
  );
}
